# Generated by Django 2.2.5 on 2019-10-10 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20191009_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo_1',
            field=models.ImageField(null=True, upload_to='photos/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='product',
            name='photo_2',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='product',
            name='photo_3',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='product',
            name='photo_4',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d'),
        ),
    ]
