# Generated by Django 2.2.5 on 2019-10-10 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20191010_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='photo_4',
        ),
        migrations.AddField(
            model_name='product',
            name='photo_main',
            field=models.ImageField(null=True, upload_to='photos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo_1',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d'),
        ),
    ]
