# Generated by Django 2.2.5 on 2019-10-10 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20191010_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='hero_photo',
            field=models.ImageField(null=True, upload_to='photos/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='category',
            name='starting_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
