# Generated by Django 2.2.5 on 2019-10-10 07:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20191010_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='list_date',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
    ]
