# Generated by Django 2.2.5 on 2019-10-11 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='starting_price',
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
