# Generated by Django 2.2.5 on 2019-10-11 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20191011_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo_main',
            field=models.ImageField(upload_to='photos/%Y/%m/%d'),
        ),
    ]
