# Generated by Django 2.2.5 on 2019-10-11 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20191011_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='banner_photo',
            field=models.ImageField(null=True, upload_to='photos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='category',
            name='starting_price',
            field=models.IntegerField(null=True),
        ),
    ]
